#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	if [ -f /usr/share/easydeskview/easydeskview ]; then
		ln -f -s /usr/share/easydeskview/easydeskview /usr/bin/easydeskview
	else
		ln -f -s /usr/share/easydeskview/rustdesk /usr/bin/easydeskview
	fi
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/easydeskview.service ]; then
			rm /etc/systemd/system/easydeskview.service /usr/lib/systemd/system/easydeskview.service /usr/lib/systemd/user/easydeskview.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/easydeskview/files/systemd/easydeskview.service /usr/lib/systemd/system/easydeskview.service
		# try fix error in Ubuntu 18.04
		# Failed to reload easydeskview.service: Unit easydeskview.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/easydeskview.service:10: Executable path is not absolute: pkill -f "easydeskview --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/easydeskview.service
		fi
		systemctl daemon-reload
		systemctl enable easydeskview
		systemctl start easydeskview
	fi
fi
